# Generated by Django 2.2.5 on 2021-03-12 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('period_date', models.DateField(verbose_name='Дата отчетного периода')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название отчета')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загружено пользователем')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('request', models.CharField(max_length=255, verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='RequestTops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_analytics.Reports', verbose_name='Отчет')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_analytics.Requests', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Позиция запроса',
                'verbose_name_plural': 'Позиции запросов',
            },
        ),
    ]
