# Generated by Django 2.2.5 on 2021-03-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_analytics', '0003_auto_20210316_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRequestTops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('request', models.CharField(max_length=255, verbose_name='Запрос')),
                ('position', models.IntegerField(verbose_name='Позиция запроса')),
            ],
        ),
    ]
