# Generated by Django 2.2.5 on 2021-03-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_analytics', '0004_temporaryrequesttops'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryrequesttops',
            name='report_id',
            field=models.IntegerField(default=1, verbose_name='ID отчета'),
            preserve_default=False,
        ),
    ]
