# Generated by Django 2.2.5 on 2021-03-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_analytics', '0005_temporaryrequesttops_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryrequesttops',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
    ]
